<a href="https://colab.research.google.com/github/Karath-Vamsi/NLP-basics/blob/main/Word_embedding_using_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [3]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
# one hot encoding
voc_size=1000
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[680, 834, 273, 350], [680, 834, 273, 459], [680, 659, 273, 602], [291, 733, 180, 895, 516], [291, 733, 180, 895, 203], [982, 680, 796, 273, 539], [338, 392, 513, 895]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
# padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 680 834 273 350]
 [  0   0   0   0 680 834 273 459]
 [  0   0   0   0 680 659 273 602]
 [  0   0   0 291 733 180 895 516]
 [  0   0   0 291 733 180 895 203]
 [  0   0   0 982 680 796 273 539]
 [  0   0   0   0 338 392 513 895]]


In [13]:
# creating an embedding layer
dim = 10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 724ms/step


array([[-0.02239746, -0.01824399, -0.01177598,  0.00277194,  0.01039684,
        -0.03914303,  0.04672184, -0.02488312, -0.01910791,  0.02675634],
       [-0.02239746, -0.01824399, -0.01177598,  0.00277194,  0.01039684,
        -0.03914303,  0.04672184, -0.02488312, -0.01910791,  0.02675634],
       [-0.02239746, -0.01824399, -0.01177598,  0.00277194,  0.01039684,
        -0.03914303,  0.04672184, -0.02488312, -0.01910791,  0.02675634],
       [-0.02239746, -0.01824399, -0.01177598,  0.00277194,  0.01039684,
        -0.03914303,  0.04672184, -0.02488312, -0.01910791,  0.02675634],
       [-0.03334149,  0.02823806, -0.03048906,  0.02215946, -0.01486676,
        -0.03543171, -0.01871197, -0.01990491, -0.03002671,  0.0058069 ],
       [-0.01905068,  0.00099443, -0.03801687,  0.01511199, -0.01964667,
        -0.03668207,  0.02761669, -0.04150029,  0.023764  , -0.00189922],
       [-0.01912125, -0.03021339,  0.01742405, -0.03340002,  0.04789079,
        -0.00620224,  0.04393006,  0.00404038